version: '3'
services:
  web:
    build: .
    container_name: 'nexmo-simple-call'
    ports:
     - '1080:3000'
    env_file:
     - .env
    volumes:
     - ./:/usr/src/app
     - /usr/src/app/node_modules
